### ISSUE TITLE
Update list of strategies

### ISSUE THREAD

**Issue by ghaiklor** [passport/www.passportjs.org#32]
How we can update strategies list?

For example, I have a lot of strategies that allows authenticate user in social networks by access token received from mobile application (it's clean REST API, so that's why I'd created strategies for this).

How can I create PR or something to add those one to strategies list ?

**Comment by jaredhanson** [comment]
To start, put links to them here. I'll make sure they are indexed for search

**Comment by ghaiklor** [comment]
@jaredhanson thanks, here the list
https://github.com/drudge/passport-facebook-token
https://github.com/drudge/passport-twitter-token
https://github.com/ghaiklor/passport-yahoo-token
https://github.com/ghaiklor/passport-google-plus-token
https://github.com/ghaiklor/passport-amazon-token
https://github.com/ghaiklor/passport-yandex-token
https://github.com/ghaiklor/passport-twitch-token
https://github.com/ghaiklor/passport-windows-live-token
https://github.com/ghaiklor/passport-soundcloud-token
https://github.com/ghaiklor/passport-reddit-token
https://github.com/ghaiklor/passport-paypal-token
https://github.com/ghaiklor/passport-instagram-token
https://github.com/ghaiklor/passport-github-token
https://github.com/ghaiklor/passport-foursquare-token
https://github.com/ghaiklor/passport-vkontakte-token

**Comment by ghaiklor** [comment]
@jaredhanson so what with this task? Can we close it or it still not added to passport strategies ?

**Comment by jaredhanson** [comment]
Many (most?) if these strategies are insecure and vulnerable to token substitution attacks.  There is no check that the client presenting the token is the client that was issued the token.

I started a branch of `passport-facebook-token` a while back that illustrates the fix:
https://github.com/jaredhanson/passport-facebook-token/blob/check-audience/lib/passport-facebook-token/strategy.js#L186

I'll add them to the list when the vulnerabilities are fixed.

**Comment by ghaiklor** [comment]
@jaredhanson `passport-facebook-token` is updated.

https://github.com/drudge/passport-facebook-token/blob/master/src/index.js#L112

And `enableProof` is enabled by default.

**Comment by ghaiklor** [comment]
@jaredhanson passport-twitter-token is also use checking for consumerKey and secret.

But how can I implement this for other social networks? I can't find any information about this in their docs.

**Comment by ghaiklor** [comment]
Closing this one as stale
