### ISSUE TITLE
Versioning Documentation

### ISSUE THREAD

**Issue by Kinnardian** [passport/www.passportjs.org#37]
@jaredhanson What do you think about versioning the documentation along the lines of the way the express.js website does it:
http://expressjs.com/4x/api.html
http://expressjs.com/3x/api.html

I think the benefit is that the old documentation is still there for people who have not updated and are therefore dependent on it.

I wanted to find out what people thought before starting any work because it did not seem like a question that could be well-packed into a single pull-request.

**Comment by jaredhanson** [comment]
There is only one Passport API, not multiple versions.  It might help to have a separate document explaining how to use Passport with Express 3.x and another for Express 4.x, but that's different that multiple versions of Passport documentation itself.

**Comment by Kinnardian** [comment]
Got it. That makes sense.
