### ISSUE TITLE
Only 5 strategies show up on http://www.passportjs.org/packages/

### ISSUE THREAD

**Issue by seshness** [passport/www.passportjs.org#65]
# Steps to repro
1. Visit http://www.passportjs.org/packages/

# Expected
300+ strategies in list, before typing anything.

# Actual
Text says "5 strategies". Only 5 boxes visible.

![image](https://user-images.githubusercontent.com/264073/33690171-3b185c9a-da97-11e7-9847-874cd567cc38.png)

**Comment by panva** [comment]
This is most definitely a feature, listing strategies from [featured.yaml](https://github.com/passport/www.passportjs.org/blob/master/data/packages/_feeds/featured.yaml) before users start typing.
