### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by FranklinYu** [passport/www.passportjs.org#75]
If I understand correctly, www.passportjs.org is running on paid plan of Heroku. If that’s the case, then [HTTPS is free](https://devcenter.heroku.com/articles/automated-certificate-management).

**Comment by chap-wong** [comment]
I am also confused why they use *.herokuapp.com certificate for their https://www.passportjs.org. Setting up Certbot and use [Letsencript](https://letsencrypt.org/) is really simple. I never use Heroku, but is it possible to use Letsencript (Completely free) on Heroku server?

**Comment by FranklinYu** [comment]
> I am also confused why they use *.herokuapp.com certificate for their https://www.passportjs.org.

Because they didn’t set up TLS, and that’s what a Heroku user gets by default.

> Setting up Certbot and use [Letsencript](https://letsencrypt.org/) is really simple.

The link I mentioned is exactly the official documentation about using Let’s Encrypt on Heroku.

**Comment by jaredhanson** [comment]
The website is now available with TLS at https://www.passportjs.org.
